spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chessdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: chess
    password: chess
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080